---
- block: # ==================RedHat==================
  - name: Install Apache for RedHat
    yum:
      name: httpd
      state: latest

  - name: Start and Enable Apache for PedHat
    service:
      name: httpd
      state: started
      enabled: yes
  when: ansible_os_family == "RedHat"

- block: # ==================Debian==================
  - name: Install Apache for Debian
    apt: name=apache2 state=latest

  - name: Start and Enable Apache for Debian
    service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"


