---
- name: Install Apache and Upload my Web Page
  hosts: "{{ MYVAR }}" # ansible-playbook playbook.yml -e "MYVAR=node-1"

  become: yes
  
  roles:
    - { role: deploy_apache, when: ansible_system == "Linux" }
